spring:
  application:
    name: study

  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url : jdbc:sqlserver://10.0.0.23:1433;database=home;encrypt=false;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username : sa
    password : xBayan!1436
